version: "3.0"
services:
  app:
    image: deneva/rna-pr:master
    container_name: app
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - '127.0.0.1:8083:80'
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql
    container_name: db
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - 'dbdir:/data'
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: 'laravelpassword'
      MYSQL_ROOT_PASSWORD: 'laravelrootpassword'
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "127.0.0.1:8036:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdir:
    driver: local
